version: '3'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
  
  backend:
    build: backend/
    ports:
      - "5000:5000"
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
  
